### ISSUE TITLE
[前馈]当模型倒数不可实现的时候我们会补充极点，这些极点有什么含义？

### ISSUE THREAD

**Issue by TaoYibo1866** [TaoYibo1866/CSD2020#5]

**Comment by Hanbinbinbin** [comment]
？？？为了让模型实现啊
相当于加高频惯性环节

**Comment by TaoYibo1866** [comment]
相当于低通滤波器，在滤波器的带宽内可以近似认为前馈通道是模型的倒数。由此我们可以知道，如果要使用前馈的话，首先要分析输入信号的频段，基于此来设计惯性环节的转折频率。我提这个问题是想告诉大家惯性环节的转折频率下限是由指令信号的频段决定的。
