### ISSUE TITLE
[噪声]计算G(jw)的等效噪声带宽时，|G(jw)|积分和Bode图的关系

### ISSUE THREAD

**Issue by CommradeStarLight** [TaoYibo1866/CSD2020#6]
RT

**Comment by TaoYibo1866** [comment]
举一个波特图积分的例子

**Comment by CommradeStarLight** [comment]
> 举一个波特图积分的例子
比如老师上课讲的这个的 积分 还提到了正负轴
![gg](https://user-images.githubusercontent.com/63098012/78346373-8c426e80-75d1-11ea-997e-7e2175e2010b.png)

**Comment by Hanbinbinbin** [comment]
我个人认为，求均方误差时是噪声的谱密度乘|G(jw)|的平方再以omega从负无穷到正无穷积分，所以上面三个操作都相当于降低积分中的|G(jw)|，所以均方误差小了，受噪声影响小了

**Comment by TaoYibo1866** [comment]
@CommradeStarLight 那个正负轴的意思是这样。计算等效噪声带宽的时候有的同学会以为只要积分-wc~wc的区间，因为他们以为这个频段外|G(jw)|是0，所以课上老师提了一句积分的时候不要只计算横轴上半部分。
