### ISSUE TITLE
[噪声]仿真中为什么加了惯性环节降低高频增益后，均方误差并没有得到很好改善？

### ISSUE THREAD

**Issue by TaoYibo1866** [TaoYibo1866/CSD2020#7]

**Comment by Hanbinbinbin** [comment]
功率传递函数中的G(jw)在实际系统中是闭环传递函数，而我们为了便于系统设计分析，是在开环传递函数上加入了高频惯性环节，虽然从开环bode图中的幅频特性曲线看，只有高频增益减小了，|G(jw)|减小了，但在闭环幅频特性曲线中，虽然高频段增益减小了，但中频段增益也被增加了，整体积分后得到的均方误差增大了。
